### ISSUE TITLE
TypeError #<Promise> is not a function.

### ISSUE THREAD

**Issue by SecurityInsanity** [Nicktho/batch-promises#10]
Trying to run an array of promises in batch-promises results in: `TypeError #<Promise> is not a function`.

For example I was able to produce this with:
```js
const batchPromises = require('batch-promises')
var promiseArr = []
for(i = 0; i < 10000; ++i) {
  promiseArr.push(new Promise((resolve) => {setTimeout(() => {resolve()}, 1000)}))
}

batchPromises(5, promiseArr, new Promise((resolve) => {
  setTimeout(() => {
    resolve()
  }, 1000)
})).then(() => {
  console.log('done')
}).catch((err) => {
  console.log(err)
})
```

Running this example produces the following output:
```js
$ node test.js 
TypeError: #<Promise> is not a function
    at Array.map (native)
    at /home/CORP.INSTRUCTURE.COM/ecoan/canvas-support-utils/node_modules/batch-promises/index.js:8:38
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Function.Module.runMain (module.js:577:11)
    at startup (node.js:159:18)
    at node.js:444:3
```

Relevant bits of info:
```
$ node --version
v6.0.0
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
```

**Comment by SecurityInsanity** [comment]
Realized that the third argument is actually a function returning a promise, and not a promise itself. Closing.
